import '../styles/globals.css'
import { ContextWrapper } from '../context/ThemeContext'
import Head from 'next/head'

function MyApp({ Component, pageProps }) {
  return <ContextWrapper> 
    <Head>
      <title>Samuel Yeebiyo | Portfolio</title>
      <link rel="icon" type="image/x-icon" href="/favicon.ico" />
      <meta name="description" content="Generated by create next app" />
      <meta property='og:title' content='Samuel Yeebiyo | Portfolio'/>
      <meta property='og:description' content='Check out my portfolio, I am a software/web developer with a passion for learning new technology and building beautiful projects.'/>
      <meta property='og:image' content='https://res.cloudinary.com/vernon2021/image/upload/v1660674421/site-snapshot_qxiygu.png'/>
      <meta property='og:url' content='https://samuel-yeebiyo.tk'/>
      <meta name="twitter:card" content="summary" />
    </Head>
    <Component {...pageProps} />
  </ContextWrapper>
}

export default MyApp
