import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

//conponents
import Navbar from '../components/Navbar/Navbar'
import Hero from '../components/Hero/Hero'
import Background from '../components/Background/Background'
import Projects from '../components/Projects/Projects'
import Contact from '../components/Contact/Contact'
import Footer from '../components/Footer/Footer'
import Skills from '../components/Skills/Skills'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Samuel Yeebiyo | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta property='og:title' content='Samuel Yeebiyo | Portfolio'/>
        <meta property='og:description' content='Check out my portfolio, I am a software/web developer with a passion for learning new technology and building beautiful projects.'/>
        <meta property='og:image' content='https://res.cloudinary.com/vernon2021/image/upload/v1660674421/site-snapshot_qxiygu.png'/>
        <meta property='og:url' content='https://samuel-yeebiyo.tk'/>
        <meta name="twitter:card" content="summary" />
        <link rel="icon" href="/assets/logo-light.png" />
      </Head>

      <main className={styles.main} style={{scrollBehavior:'smooth'}} id={"main"}>
        <Navbar/>
        <div className={styles.content}>
          <Hero/>
          <Background/>
          <Projects/>
          <Skills/>
          <Contact/>
        </div>
      </main>

      <Footer/>
    </div>
  )
}
