import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar/Navbar'
import Hero from '../components/Hero/Hero'
import Background from '../components/Background/Background'
import Projects from '../components/Projects/Projects'
import Contact from '../components/Contact/Contact'
import Footer from '../components/Footer/Footer'
import Skills from '../components/Skills/Skills'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Samuel Yeebiyo | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/logo-light.png" />
      </Head>

      <main className={styles.main} style={{scrollBehavior:'smooth'}}>
        <Navbar/>
        <Hero/>
        <Background/>
        <Projects/>
        <Skills/>
        <Contact/>
      </main>

      <Footer/>
    </div>
  )
}
